-- MySQL Script generated by MySQL Workbench
-- Wed Jan  9 17:02:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RyTH
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RyTH
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RyTH` DEFAULT CHARACTER SET utf8 ;
USE `RyTH` ;

-- -----------------------------------------------------
-- Table `RyTH`.`Estaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RyTH`.`Estaciones` (
  `idEstaciones` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Lugar` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstaciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RyTH`.`Departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RyTH`.`Departamentos` (
  `idDepartamentos` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `idEstaciones` INT NOT NULL,
  PRIMARY KEY (`idDepartamentos`),
  INDEX `fk_Departamentos_Estaciones1_idx` (`idEstaciones` ASC) ,
  CONSTRAINT `fk_Departamentos_Estaciones1`
    FOREIGN KEY (`idEstaciones`)
    REFERENCES `RyTH`.`Estaciones` (`idEstaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RyTH`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RyTH`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `idDepartamentos` INT NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Puesto` VARCHAR(30) NOT NULL,
  `Calle` VARCHAR(50) NOT NULL,
  `No` VARCHAR(5) NOT NULL,
  `Col` VARCHAR(25) NOT NULL,
  `Localidad` VARCHAR(40) NOT NULL,
  `Telefono` VARCHAR(15) NOT NULL,
  `Ext` VARCHAR(8) NULL,
  `Fax` VARCHAR(20) NULL,
  `E-mail` VARCHAR(25) NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Departamentos1_idx` (`idDepartamentos` ASC) ,
  CONSTRAINT `fk_Usuario_Departamentos1`
    FOREIGN KEY (`idDepartamentos`)
    REFERENCES `RyTH`.`Departamentos` (`idDepartamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RyTH`.`MobiliarioyEquipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RyTH`.`MobiliarioyEquipo` (
  `id` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `No.Inv.` VARCHAR(15) NOT NULL,
  `Descripcion` VARCHAR(60) NOT NULL,
  `Color` VARCHAR(15) NOT NULL,
  `Material` VARCHAR(15) NOT NULL,
  `Marca` VARCHAR(15) NOT NULL,
  `Modelo` VARCHAR(15) NOT NULL,
  `Serie` VARCHAR(20) NOT NULL,
  `Tipo` VARCHAR(15) NOT NULL,
  `Status` VARCHAR(15) NOT NULL,
  `idFactura` VARCHAR(12) NOT NULL,
  `FormaCompra` VARCHAR(25) NOT NULL,
  `Origen` VARCHAR(35) NOT NULL,
  `CostoCIVA` DOUBLE NOT NULL,
  `CostoSIVA` DOUBLE NOT NULL,
  `FechaCompra` DATE NOT NULL,
  `Observaciones` VARCHAR(60) NOT NULL,
  `IVA` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mobiliarioyequipo_Usuario1_idx` (`idUsuario` ASC) ,
  CONSTRAINT `fk_mobiliarioyequipo_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `RyTH`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RyTH`.`Vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RyTH`.`Vehiculos` (
  `Serie` VARCHAR(20) NOT NULL,
  `idUsuario` INT NOT NULL,
  `Marca` VARCHAR(10) NOT NULL,
  `Tipo` VARCHAR(20) NOT NULL,
  `Modelo` VARCHAR(4) NOT NULL,
  `Placas` VARCHAR(15) NOT NULL,
  `No.Inv.` VARCHAR(8) NOT NULL,
  `Motor` VARCHAR(13) NOT NULL,
  `Color` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Serie`),
  INDEX `fk_vehiculos_Usuario1_idx` (`idUsuario` ASC) ,
  CONSTRAINT `fk_vehiculos_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `RyTH`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RyTH`.`Partes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RyTH`.`Partes` (
  `idPartes` INT NOT NULL,
  `vehiculos_Serie` VARCHAR(20) NOT NULL,
  `Tiene` ENUM('Si', 'No') NOT NULL,
  `Estado` ENUM('Bueno', 'Malo') NULL,
  `Observaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`idPartes`),
  INDEX `fk_PartesCarro_vehiculos_idx` (`vehiculos_Serie` ASC) ,
  CONSTRAINT `fk_PartesCarro_vehiculos`
    FOREIGN KEY (`vehiculos_Serie`)
    REFERENCES `RyTH`.`Vehiculos` (`Serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RyTH`.`UsuarioSistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RyTH`.`UsuarioSistema` (
  `idUsuariosSistema` INT NOT NULL,
  `User` VARCHAR(15) NOT NULL,
  `Password` VARCHAR(15) NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idUsuariosSistema`),
  INDEX `fk_UsuariosSistema_Usuario1_idx` (`idUsuario` ASC) ,
  CONSTRAINT `fk_UsuariosSistema_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `RyTH`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RyTH`.`SOTSBI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RyTH`.`SOTSBI` (
  `idSOTSBI` INT NOT NULL,
  `Solicitante` INT NOT NULL,
  `Responsable` INT NOT NULL,
  `Codigo` VARCHAR(10) NOT NULL,
  `Revision` VARCHAR(5) NOT NULL,
  `NoSolicitud` INT NOT NULL ,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`idSOTSBI`),
  INDEX `fk_SOTSBI_Usuario1_idx` (`Solicitante` ASC) ,
  INDEX `fk_SOTSBI_Usuario2_idx` (`Responsable` ASC) ,
  CONSTRAINT `fk_SOTSBI_Usuario1`
    FOREIGN KEY (`Solicitante`)
    REFERENCES `RyTH`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SOTSBI_Usuario2`
    FOREIGN KEY (`Responsable`)
    REFERENCES `RyTH`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RyTH`.`SOTSBI_has_MobiliarioyEquipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RyTH`.`SOTSBI_has_MobiliarioyEquipo` (
  `SOTSBI_idSOTSBI` INT NOT NULL,
  `MobiliarioyEquipo_id` INT NOT NULL,
  `Estado` VARCHAR(15) NOT NULL,
  `MotivoBaja` VARCHAR(15) NOT NULL,
  `Observaciones` VARCHAR(100) NOT NULL,
  INDEX `fk_SOTSBI_has_MobiliarioyEquipo_MobiliarioyEquipo1_idx` (`MobiliarioyEquipo_id` ASC) ,
  INDEX `fk_SOTSBI_has_MobiliarioyEquipo_SOTSBI1_idx` (`SOTSBI_idSOTSBI` ASC) ,
  CONSTRAINT `fk_SOTSBI_has_MobiliarioyEquipo_SOTSBI1`
    FOREIGN KEY (`SOTSBI_idSOTSBI`)
    REFERENCES `RyTH`.`SOTSBI` (`idSOTSBI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SOTSBI_has_MobiliarioyEquipo_MobiliarioyEquipo1`
    FOREIGN KEY (`MobiliarioyEquipo_id`)
    REFERENCES `RyTH`.`MobiliarioyEquipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RyTH`.`Traspaso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RyTH`.`Traspaso` (
  `idTraspaso` INT NOT NULL,
  `UsuarioPrecedencia` INT NOT NULL,
  `UsuarioDestino` INT NOT NULL,
  `MobiliarioyEquipo_id` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`idTraspaso`),
  INDEX `fk_Traspaso_Usuario1_idx` (`UsuarioPrecedencia` ASC) ,
  INDEX `fk_Traspaso_Usuario2_idx` (`UsuarioDestino` ASC) ,
  INDEX `fk_Traspaso_MobiliarioyEquipo1_idx` (`MobiliarioyEquipo_id` ASC) ,
  CONSTRAINT `fk_Traspaso_Usuario1`
    FOREIGN KEY (`UsuarioPrecedencia`)
    REFERENCES `RyTH`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Traspaso_Usuario2`
    FOREIGN KEY (`UsuarioDestino`)
    REFERENCES `RyTH`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Traspaso_MobiliarioyEquipo1`
    FOREIGN KEY (`MobiliarioyEquipo_id`)
    REFERENCES `RyTH`.`MobiliarioyEquipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RyTH`.`TraspasoVehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RyTH`.`TraspasoVehiculos` (
  `idTraspasoVehiculos` VARCHAR(45) NOT NULL,
  `UsuarioProcedencia` INT NOT NULL,
  `UsuarioDestino` INT NOT NULL,
  `Vehiculos_Serie` VARCHAR(20) NOT NULL,
  `Fecha` DATE NOT NULL,
  INDEX `fk_TraspasoVehiculos_Usuario1_idx` (`UsuarioProcedencia` ASC) ,
  INDEX `fk_TraspasoVehiculos_Usuario2_idx` (`UsuarioDestino` ASC) ,
  INDEX `fk_TraspasoVehiculos_Vehiculos1_idx` (`Vehiculos_Serie` ASC) ,
  PRIMARY KEY (`idTraspasoVehiculos`),
  CONSTRAINT `fk_TraspasoVehiculos_Usuario1`
    FOREIGN KEY (`UsuarioProcedencia`)
    REFERENCES `RyTH`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TraspasoVehiculos_Usuario2`
    FOREIGN KEY (`UsuarioDestino`)
    REFERENCES `RyTH`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TraspasoVehiculos_Vehiculos1`
    FOREIGN KEY (`Vehiculos_Serie`)
    REFERENCES `RyTH`.`Vehiculos` (`Serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RyTH`.`SolicitudReparacioMov`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RyTH`.`SolicitudReparacioMov` (
  `idtable1` INT NOT NULL,
  `Responsable` INT NOT NULL,
  `Solicitante` INT NOT NULL,
  `MobiliarioyEquipo_id` INT NOT NULL,
  `FechaIngreso` DATE NOT NULL,
  `FechaSalida` DATE NULL,
  PRIMARY KEY (`idtable1`),
  INDEX `fk_SolicitudReparaciob_Usuario1_idx` (`Responsable` ASC) ,
  INDEX `fk_SolicitudReparaciob_Usuario2_idx` (`Solicitante` ASC) ,
  INDEX `fk_SolicitudReparaciob_MobiliarioyEquipo1_idx` (`MobiliarioyEquipo_id` ASC) ,
  CONSTRAINT `fk_SolicitudReparaciob_Usuario1`
    FOREIGN KEY (`Responsable`)
    REFERENCES `RyTH`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SolicitudReparaciob_Usuario2`
    FOREIGN KEY (`Solicitante`)
    REFERENCES `RyTH`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SolicitudReparaciob_MobiliarioyEquipo1`
    FOREIGN KEY (`MobiliarioyEquipo_id`)
    REFERENCES `RyTH`.`MobiliarioyEquipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RyTH`.`SolicitudReparacionV`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RyTH`.`SolicitudReparacionV` (
  `idSolicitudReparacionV` INT NOT NULL,
  `Solicitante` INT NOT NULL,
  `Vehiculos_Serie` VARCHAR(20) NOT NULL,
  `FechaIngreso` DATE NOT NULL,
  `FechaSalida` DATE NULL,
  `Taller` VARCHAR(60) NOT NULL,
  `TelefonoTaller` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idSolicitudReparacionV`),
  INDEX `fk_SolicitudReparacionV_Usuario1_idx` (`Solicitante` ASC) ,
  INDEX `fk_SolicitudReparacionV_Vehiculos1_idx` (`Vehiculos_Serie` ASC) ,
  CONSTRAINT `fk_SolicitudReparacionV_Usuario1`
    FOREIGN KEY (`Solicitante`)
    REFERENCES `RyTH`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SolicitudReparacionV_Vehiculos1`
    FOREIGN KEY (`Vehiculos_Serie`)
    REFERENCES `RyTH`.`Vehiculos` (`Serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RyTH`.`SOTSBI_has_Vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RyTH`.`SOTSBI_has_Vehiculos` (
  `SOTSBI_idSOTSBI` INT NOT NULL,
  `Vehiculos_Serie` VARCHAR(20) NOT NULL,
  `Estado` VARCHAR(15) NOT NULL,
  `MotivoBaja` VARCHAR(15) NOT NULL,
  `Observaciones` VARCHAR(100) NOT NULL,
  INDEX `fk_SOTSBI_has_Vehiculos_Vehiculos1_idx` (`Vehiculos_Serie` ASC) ,
  INDEX `fk_SOTSBI_has_Vehiculos_SOTSBI1_idx` (`SOTSBI_idSOTSBI` ASC) ,
  CONSTRAINT `fk_SOTSBI_has_Vehiculos_SOTSBI1`
    FOREIGN KEY (`SOTSBI_idSOTSBI`)
    REFERENCES `RyTH`.`SOTSBI` (`idSOTSBI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SOTSBI_has_Vehiculos_Vehiculos1`
    FOREIGN KEY (`Vehiculos_Serie`)
    REFERENCES `RyTH`.`Vehiculos` (`Serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
